version: '3.9'

services:
  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: mindiooU
      POSTGRES_PASSWORD: mindiooP
      POSTGRES_DB: mindiooDB
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}