version: '3.9'

services:

  backend:
    container_name: backend
    image: backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL="postgresql://mindiooU:mindiooP@localhost:5432/mindiooDB?schema=public"

  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: mindiooU
      POSTGRES_PASSWORD: mindiooP
      POSTGRES_DB: mindiooDB
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}